// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3aEiP_axACHyuib1GaqaqLqjJFPtGvMo',
    appId: '1:942983480059:web:b901d53023cee3380f665e',
    messagingSenderId: '942983480059',
    projectId: 'chat-messaging-firebase',
    authDomain: 'chat-messaging-firebase.firebaseapp.com',
    storageBucket: 'chat-messaging-firebase.firebasestorage.app',
    measurementId: 'G-GBG806KYH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCA7WBLMPsSnTKUUYxptBQI-GYbUSaw8',
    appId: '1:942983480059:android:8fdcf9953ebd871f0f665e',
    messagingSenderId: '942983480059',
    projectId: 'chat-messaging-firebase',
    storageBucket: 'chat-messaging-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRGA6_bBLu0KnTXbUlFZw14ESwQQrPLU',
    appId: '1:942983480059:ios:6adb416e5f7e783b0f665e',
    messagingSenderId: '942983480059',
    projectId: 'chat-messaging-firebase',
    storageBucket: 'chat-messaging-firebase.firebasestorage.app',
    iosBundleId: 'com.example.chatMessagingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRGA6_bBLu0KnTXbUlFZw14ESwQQrPLU',
    appId: '1:942983480059:ios:6adb416e5f7e783b0f665e',
    messagingSenderId: '942983480059',
    projectId: 'chat-messaging-firebase',
    storageBucket: 'chat-messaging-firebase.firebasestorage.app',
    iosBundleId: 'com.example.chatMessagingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3aEiP_axACHyuib1GaqaqLqjJFPtGvMo',
    appId: '1:942983480059:web:8fcd7bcad254ae340f665e',
    messagingSenderId: '942983480059',
    projectId: 'chat-messaging-firebase',
    authDomain: 'chat-messaging-firebase.firebaseapp.com',
    storageBucket: 'chat-messaging-firebase.firebasestorage.app',
    measurementId: 'G-VXBSQYRCFB',
  );
}
