import 'dart:io';

import 'package:chat_messaging_firebase/chats/chat_list.dart';
import 'package:chat_messaging_firebase/login/authenticate.dart';
import 'package:chat_messaging_firebase/login/helper_functions.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    return super.createHttpClient(context)
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
  HttpOverrides.global = MyHttpOverrides();
  // Get.put(HomeController());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool userIsLoggedIn = false;

  @override
  void initState() {
    getLoggedInState();
    super.initState();
  }

  getLoggedInState() async {
    await HelperFunctions.getUserLoggedInSharedPreference().then((value) {
      setState(() {
        userIsLoggedIn = value ?? false;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Check In Chick',
      debugShowCheckedModeBanner: false,
      // theme: AppTheme.appTheme(context),
      home:
          userIsLoggedIn != null
              ? userIsLoggedIn
                  ? ChatsList()
                  : Authenticate()
              : Container(child: Center(child: Authenticate())),
    );
  }
}
